services:
  mysql-portella-db:
    image: mysql:8.0
    container_name: mysql-portella-db
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: "$DB_NAME"
    ports:
      - $DB_PORT:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
